[options]
top top

[read]
read -sv loop.svi

[file loop.svi]
module top(input a);

    invariant always_a;
        a;
    endinvariant

    invariant a_always;
        a;
    endinvariant

    automatic proof prove_always_a;
        cross assume invariant a_always;
        assert invariant always_a;
    endproof

    automatic proof prove_a_always;
        cross assume invariant always_a;
        assert invariant a_always;
    endproof

endmodule
