[options]
top top

[read]
read -sv example.svi


[file example.svi]
module top;

    wire a = 1;

    wire b = a;

    invariant always_a;
        a;
    endinvariant

    invariant always_b;
        b;
    endinvariant

    proof b_via_a;
        assert invariant always_b;
        solve with "dummy unknown -d 1" priority 1;
        solve with "dummy fail -d 4" priority 0;
        solve with "dummy pass -d 2" priority (-1);
    endproof

    solve proof b_via_a;
endmodule
